Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AskMate2.Domain;
using AskMate2.Models;
using AskMate2.Controllers;
using Microsoft.AspNetCore.Authorization;

namespace AskMate2.Controllers
{
    
    public class AnswersController : Controller
    {
        IDataService ds = new DBService();
        [Authorize]
        [HttpGet]
        public IActionResult AddAnswer()
        {
            foreach (Question question in ds.GetQuestions())
            {
                ViewData.Add(question.Id.ToString(), question.Id.ToString() + ": " + question.Title);
            }
            return View("AddAnswer");
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddAnswer([FromForm(Name = "question")] string question)
        {
            string text = "";
            string id = question.Split(":").ToArray()[0];
            foreach (Question que in ds.GetQuestions())
            {
                if (que.Id == id)
                {
                    text = que.Text;
                }
            }
            ViewData.Add(question, text);
            return View("Answer"); 
        }

        [Authorize]
        public IActionResult NewAnswer([FromForm(Name = "answer")] string answer, [FromForm(Name = "qID")] string qID, [FromForm(Name = "image")] string image, [FromForm(Name = "currentUser")] string currentUser)
        {
            if (image == null || !image.StartsWith("https://"))
            {
                image = "https://";
            }
            ds.AddAnswer(ds.MakeAnswerWoId(qID, currentUser, answer, image));
            //foreach (Question question in ds.GetQuestions())
            //{
            //    ViewData.Add(question.Id.ToString(), question.Title);
            //}
            return RedirectToAction("ShowQe", "Questions", new { qid = QuestionsController.focusQid }); ;
        }

        [Authorize]
        [HttpGet]
        public IActionResult ShowAnswers()
        {
            foreach (Question question in ds.GetQuestions())
            {
                ViewData.Add(question.Id.ToString(), question.Id.ToString() + ": " + question.Title);
            }
            return View("ShowAnswers");
        }

        [Authorize]
        [HttpPost]
        public IActionResult ShowAnswers([FromForm(Name = "question")] string question)
        {
            string text = "";
            List<Transit> transitLst = new List<Transit>();
            string id = question.Split(":").ToArray()[0];
            string qtext = "";
            foreach (Question que in ds.GetQuestions())
            {
                if (id == que.Id)
                {
                    Transit transit = new Transit();
                    transit.Qid = id.ToString();
                    transit.Qtitle = question.Split(":").ToArray()[1];
                    transit.Qtext = que.Text;
                    List<Answer> answers = ds.GetAnswers(que.Id);

                    foreach (Answer answer in answers)
                    {
                        text = answer.Text;
                        transit.Aid = answer.AId.ToString();
                        transit.Atext = answer.Text;
                        transitLst.Add(transit); 
                    }
                }
            }
            
            return View("ShowA", transitLst);
        }

        [Authorize]
        [HttpGet]
        public IActionResult DeleteAnswer()
        {
            foreach (Question question in ds.GetQuestions())
            {
                ViewData.Add(question.Id.ToString(), question.Id.ToString() + ": " + question.Title);
            }
            return View("DeleteAnswer");
        }

        [Authorize]
        [HttpPost]
        public IActionResult DeleteAnswer([FromForm(Name = "question")] string question)
        {
            string text = "";
            List<Transit> transitLst = new List<Transit>();
            string id = question.Split(":").ToArray()[0];
            string qtext = "";
            foreach (Question que in ds.GetQuestions())
            {
                if (id == que.Id)
                {
                    qtext = que.Text;
                }
            }
            foreach (Answer answer in ds.GetAnswers(id))
            {
                if (answer.QId == id)
                {
                    Transit transit = new Transit();
                    text = answer.Text;
                    transit.Qid = id.ToString();
                    transit.Aid = answer.AId.ToString();
                    transit.Qtitle = question.Split(":").ToArray()[1];
                    transit.Qtext = qtext;
                    transit.Atext = answer.Text;
                    transitLst.Add(transit);
                }
            }
            return View("DeleteA", transitLst);

        }

        [Authorize]
        public IActionResult DelAnswer([FromForm(Name = "Aid")] string Aid)
        {
            ds.DeleteAnswer(Aid);
            return RedirectToAction("Index","Home");
        }

        [Authorize]
        [HttpGet]
        public IActionResult AnswerVote()
        {
            return View("VoteAnswer");
        }

        [Authorize]
        [HttpPost]
        public IActionResult AnswerVote([FromForm(Name = "aId")] string answerId)
        {
            ds.AnswerVote(answerId);
            var uId = ds.GetUserFromAnswer(answerId);
            ds.IncreaseReputation(uId, 10);
            return RedirectToAction("ShowQe", "Questions", new { qid = QuestionsController.focusQid });
        }
        
        [Authorize]
        [HttpGet]
        public IActionResult AnswerDownVote()
        {
            return View("VoteAnswer");
        }

        [Authorize]
        [HttpPost]
        public IActionResult AnswerDownVote([FromForm(Name = "aId")] string answerId)
        {
            ds.AnswerDownVote(answerId);
            var uId = ds.GetUserFromAnswer(answerId);
            ds.DecreaseReputation(uId, 2);
            return RedirectToAction("ShowQe", "Questions", new { qid = QuestionsController.focusQid });
        }


        [Authorize]
        [HttpPost]
        public IActionResult AddImageToAnswer([FromForm(Name = "image")] string image, [FromForm(Name = "aid")] string answerId)
        {
            if (image == null || !image.StartsWith("https://"))
            {
                image = "https://";
            }
            ds.AddImageToAnswer(answerId, (image));
            return RedirectToAction("ShowQe", "Questions", new { qid = QuestionsController.focusQid });
        }

        [Authorize]
        [HttpGet]
        public IActionResult CommentToAnswer()
        {
            return View("CommentToAnswer");
        }

        [Authorize]
        [HttpPost]
        public IActionResult CommentToAnswer([FromForm(Name = "answerId")] string answerId, [FromForm(Name = "comment")] string comment, [FromForm(Name = "currentUser")] string currentUser)
        {
            ds.AddCommentAnswer(answerId, comment, currentUser);
            return RedirectToAction("ShowQe", "Questions", new { qid = QuestionsController.focusQid }); //EDIT (according to specifications)
        }



        [Authorize]
        [HttpGet]
        public IActionResult EditCommentAnswer()
        {
            return View("EditCommentAnswer");
        }

        [Authorize]
        [HttpPost]
        public IActionResult EditCommentAnswer([FromForm(Name = "answerId")] string answerId, [FromForm(Name = "komment")] string komment)
        {
            ds.EditCommentAnswer(answerId, komment);
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpPost]
        public IActionResult EditAnswer([FromForm(Name = "Aid")] string answerId)
        {
            Transit transit = new Transit();
            Answer answer = ds.GetAnswer(answerId);
            transit.Aid = answer.AId;
            transit.AUserId = answer.AUserId;
            transit.Qid = answer.QId;
            transit.AsubmissionTime = answer.SubmissionTime;
            transit.Atext = answer.Text;
            transit.Aimage = answer.Image;
            transit.Aaccepted = answer.Aaccepted;
            return View("EditAnswer", transit);
        }

        [Authorize]
        [HttpPost]
        public IActionResult EditAnswer2([FromForm(Name = "Aid")] string answerId, [FromForm(Name = "message")] string message, [FromForm(Name = "image")] string image)
        {
            ds.EditAnswer(answerId, message, image);
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpPost]
        public IActionResult AcceptedAnswer([FromForm(Name = "aId")] string aId)
        {
            ds.AccepAnswer(aId);
            var uid = ds.GetUserFromAnswer(aId);
            ds.IncreaseReputation(uid, 15);
            return RedirectToAction("ShowQe", "Questions", new { qid = QuestionsController.focusQid });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AskMate2.Models;
using AskMate2.Domain;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace AskMate2.Controllers
{
    public class HomeController : Controller
    {
        IDataService ds = new DBService();
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            string currentUser = "";
            currentUser = ds.GetUserId(HttpContext.User.FindFirstValue(ClaimTypes.Email));
            ViewData.Add("currentUser", currentUser);
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult AboutUs()
        {
            return View();
        }

        [Authorize]
        public IActionResult Theeye()
        {
            string email = HttpContext.User.FindFirstValue(ClaimTypes.Email);
            ViewData.Add("email", email);
            return View("devspage");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SinglePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AskMate2.Controllers
{
    public class SinglePageController : Controller
    {
        public IActionResult SinglePage()
        {
            return View();
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AskMate2;
using AskMate2.Domain;
using AskMate2.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace AskMate2.Controllers
{
    [Microsoft.AspNetCore.Components.Route("")]
    public class UserController : Controller 
    { 
        public static string focusQid = "";
        IDataService ds = new DBService();

        [Authorize]
        [HttpGet]
        public IActionResult user()
        {
            string currentUser = ds.GetUserId(HttpContext.User.FindFirstValue(ClaimTypes.Email));
            ViewData.Add("currentUser", currentUser);
            QAC qac = ds.GetQACByUserId(currentUser);
            return View("user", qac);
        }
    }
}

Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "About Us?";
}
<h1>@ViewData["Title"]</h1>
<h4>Don't be nosey!</h4>

Views/Home/Index.cshtml
<div class="mainpage">
    @{
        string username = "unknown";
        if (ViewData["currentUser"].ToString() != "")
        {
            username = ViewData["currentUser"].ToString();
        }
        else
        {
            username = "stranger";
        }
    }
    <div class="currentUser">
        @{<p>Welcome @username !</p>
            if (username != "stranger")
            {
                <a asp-controller="User" asp-action="user">Your activity -></a>
            }
        }
    </div>
    <div class="kozepre">
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <a asp-controller="Questions" asp-action="ListQuestions">
            <h1 class="bigcenter">If you didn't know,...now you know.</h1>
            <!--<img class="biglogo" src="~/braintree.png" alt="Transparent Background Questions And Answers Clipart" />-->
        </a>
        <a asp-controller="Home" asp-action="Theeye">
            <img class="theeye" src="~/theeye.png" alt="All Seeing Eye Transparent Png - Novus Ordo Seclorum Vector" />
        </a>
    </div>
</div>

Views/Home/devspage.cshtml
@{
    ViewData["Title"] = "devspage";
}

<h1>devspage</h1>
<br />
<p>principal: @ViewData["email"]</p>

<h4>Test functions</h4>
<ul>
    <li><a asp-controller="Questions" asp-action="ListQuestions">List all questions</a></li>
    <li><a asp-controller="Questions" asp-action="ShowQuestion">Show a question</a></li>
    <li><a asp-controller="Questions" asp-action="AddQuestion">Add a new question</a></li>
    <li><a asp-controller="Questions" asp-action="EditQuestion1">Edit a question</a></li>
    <li><a asp-controller="Questions" asp-action="DeleteQuestion">Delete a question</a></li>
    <li><a asp-controller="Questions" asp-action="Vote">Vote on Question</a></li>
    <li><a asp-controller="Questions" asp-action="CommentToQuestion">Comment on a question</a></li>
    <li><a asp-controller="Questions" asp-action="AddImageToQuestion">Add Image to question</a></li>
    <li><a asp-controller="Questions" asp-action="EditCommentQuestion">Edit comment on question</a></li>
    <li><a asp-controller="Questions" asp-action="DeleteCommentQuestion">Delete comment on question</a></li>
    <li><a asp-controller="Answers" asp-action="ShowAnswers">Show answers for a question</a></li>
    <li><a asp-controller="Answers" asp-action="AddAnswer">Add an answer</a></li>
    <li><a asp-controller="Answers" asp-action="DeleteAnswer">Delete an answer</a></li>
    <li><a asp-controller="Answers" asp-action="AnswerVote">Vote for an answer</a></li>
    <li><a asp-controller="Answers" asp-action="CommentToAnswer">Comment on an answer</a></li>
    <li><a asp-controller="Answers" asp-action="EditCommentAnswer">Edit comment on answer</a></li>
    <li><a asp-controller="Answers" asp-action="EditAnswer">Edit answer</a></li>
    <li><a asp-controller="SinglePage" asp-action="SinglePage">SinglePage design</a></li>

</ul>